apiVersion: v1
kind: Namespace
metadata:
  name: projectsveltos
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: register-mgmt-cluster
  namespace: projectsveltos
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: register-mgmt-cluster-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: register-mgmt-cluster
  namespace: projectsveltos
---
apiVersion: batch/v1
kind: Job
metadata:
  name: register-mgmt-cluster-job
  namespace: projectsveltos
spec:
  template:
    spec:
      containers:
      - name: register-mgmt-cluster
        image: projectsveltos/register-mgmt-cluster:v0.28.0
        imagePullPolicy: IfNotPresent
        args:
        - --labels=
        resources:
          requests:
            memory: 128Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
      serviceAccountName: register-mgmt-cluster
      restartPolicy: Never
  backoffLimit: 4
---
